from TreeVisitor import TreeVisitor
from TreeParser import TreeParser


class MyTreeVisitor(TreeVisitor):
    """Visitor that evaluates an expression. Derives and overrides methods
    from TreeVisitor (generated by ANTLR4)."""

    def __init__(self):
        pass

    def visitTop(self, ctx):
        return self.visit(ctx.int_tree())

    def visitLeaf(self, ctx):
        print("   leaf : "+ctx.getText())
        return True

    def visitNode(self, ctx):
        # root = ctx.INT().getText()
        try:
            tree2 = self.visit(ctx.int_tree(2))
            return False
        except AttributeError:
            tree0 = self.visit(ctx.int_tree(0))
            try:
                return self.visit(ctx.int_tree(1)) and tree0
            except AttributeError:
                return tree0
